# Generated by Django 5.0.1 on 2024-01-22 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='titel',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.projects'),
            preserve_default=False,
        ),
    ]
