# Generated by Django 5.0.1 on 2024-01-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_complete',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_complete',
            field=models.BooleanField(default=False),
        ),
    ]
